[package]
name = "day20"
version = "0.1.0"
authors = ["Dat Truong <mr.anhdat@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = ""
lazy_static = ""
itertools = ""
